### ISSUE TITLE
crash on logout

### ISSUE THREAD

**Issue by otakup0pe** [tribesthatmaybe/modpack#1]
```
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.mrcrayfish.guns.object.Bullet.tick(Bullet.java:55)
	at com.mrcrayfish.guns.client.event.RenderEvents.lambda$onTickBullets$0(RenderEvents.java:1040)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.mrcrayfish.guns.client.event.RenderEvents.onTickBullets(RenderEvents.java:1040)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_860_RenderEvents_onTickBullets_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

only putting this here so we don't forget 😈

**Comment by otakup0pe** [comment]
based it what it says on the tin https://github.com/MrCrayfish/MrCrayfishGunMod/issues/35 matches but the crashlogs are on dead links 💀

**Comment by otakup0pe** [comment]
also pretty sure this https://github.com/MrCrayfish/MrCrayfishGunMod/pull/54 is literally the same stack

**Comment by otakup0pe** [comment]
oh hey this again
