### ISSUE TITLE
localized chat chokes on customnpc world lines

### ISSUE THREAD

**Issue by otakup0pe** [tribesthatmaybe/modpack#12]
Oddly enough doesn't seem to be a problem with the interaction lines?

```
[22:41:00] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.ServerChatEvent@289a1da:
java.lang.NullPointerException: null
        at com.kreezcraft.localizedchat.ChatListener.onChat(ChatListener.java:59) ~[ChatListener.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2101_ChatListener_onChat_ServerChatEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) ~[LagGoggles-1.12.2-5.8-132.jar:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at noppes.npcs.entity.EntityNPCInterface.saySurrounding(EntityNPCInterface.java:949) [EntityNPCInterface.class:?]
        at noppes.npcs.ai.EntityAIWorldLines.func_75249_e(EntityAIWorldLines.java:27) [EntityAIWorldLines.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102) [xf.class:?]
        at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) [vq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) [vp.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [vq.class:?]
        at noppes.npcs.entity.EntityNPCInterface.func_70636_d(EntityNPCInterface.java:425) [EntityNPCInterface.class:?]
        at net.minecraft.entity.EntityLivingBase.TickCentral_TrueOnUpdateTick(EntityLivingBase.java:2179) [vp.class:?]
        at net.minecraft.entity.EntityLiving.TickCentral_TrueOnUpdateTick(EntityLiving.java:295) [vq.class:?]
        at noppes.npcs.entity.EntityNPCInterface.TickCentral_TrueOnUpdateTick(EntityNPCInterface.java:297) [EntityNPCInterface.class:?]
        at noppes.npcs.entity.EntityCustomNpc.TickCentral_TrueOnUpdateTick(EntityCustomNpc.java:50) [EntityCustomNpc.class:?]
        at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56) [TickHub.class:?]
        at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:102) [LagGoggles-1.12.2-5.8-132.jar:?]
        at noppes.npcs.entity.EntityCustomNpc.func_70071_h_(EntityCustomNpc.java) [EntityCustomNpc.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1996) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1958) [amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1762) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```
Looking at [this](https://github.com/kreezxil/Localized-Chat/blob/1.12.2/src/main/java/com/kreezcraft/localizedchat/ChatListener.java) line I think it's because the localized chat mod is expecting a certain interface that it ain't getting from the NPC.

Given the choice of localized chat and npcs, I'd probably pick the latter.

**Comment by otakup0pe** [comment]
Filed something [upstream](https://github.com/kreezxil/Localized-Chat/issues/6) and pull localized chat for now.

**Comment by otakup0pe** [comment]
Seems to have been fixed upstream, will take a look.

**Comment by otakup0pe** [comment]
seems like the upstream fix has worked, at least i haven't seen any crashes in a bit since re-enabling it despite hanging around old blood and third year joe a bunch.
