### ISSUE TITLE
crash on new chunks

### ISSUE THREAD

**Issue by otakup0pe** [tribesthatmaybe/modpack#2]
```
Stacktrace:
	at net.minecraft.util.EnumFacing.func_176735_f(EnumFacing.java:167)
	at blusunrize.immersiveengineering.common.blocks.TileEntityIEBase.func_189667_a(TileEntityIEBase.java:92)
	at ivorius.reccomplex.temp.RCPosTransformer.transformAdditionalData(RCPosTransformer.java:29)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.setBlock(GenericStructure.java:125)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:214)
	at ivorius.reccomplex.world.gen.feature.structure.generic.GenericStructure.generate(GenericStructure.java:71)
	at ivorius.reccomplex.world.gen.feature.StructureGenerator.generate(StructureGenerator.java:219)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.planStructureInChunk(WorldGenStructures.java:120)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.lambda$planStructuresInChunk$2(WorldGenStructures.java:77)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.planStructuresInChunk(WorldGenStructures.java:77)
	at ivorius.reccomplex.world.gen.feature.WorldGenStructures.decorate(WorldGenStructures.java:222)
	at ivorius.reccomplex.events.handlers.RCForgeEventHandler.onPreChunkDecoration(RCForgeEventHandler.java:85)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1361_RCForgeEventHandler_onPreChunkDecoration_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:769)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:395)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
```

I sense this is related to recurrent complex and one of the structures I've been playing with. Haven't been able to repro yet.

**Comment by otakup0pe** [comment]
The `cache1` rc structure was set to rotate and has some ie shit in it. Set it to not rotate, hoping that helps.

**Comment by otakup0pe** [comment]
It seems to have helped? Gonna give it another week before closing.

**Comment by otakup0pe** [comment]
Calling this done now bc we aren't crasihng. Do still see occasional timeouts though, but that will be a separate issue.
